### n-th root of a number

Halley’s method computes a root of a function $f(x)$ by applying:


\begin{cases}
    x_{i+1} = x_i - \dfrac{2 f(x_i) f'(x_i)}{2[f'(x_i)]^2 - f(x_i) f''(x_i)} \\
    x_0 \in [a,b]
\end{cases}

If we apply this to:

$$
    f(x) = x^n - k
$$

We obtain an iterative formula to get the $n$-th root of $k$:

$$
    x_{i+1} = x_i \, \frac{(n-1)x_i^n + (n+1)k} {(n+1)x_i^n + (n-1)k}
$$

For the square root, i.e. $n=2$, this becomes:

$$
    x_{i+1} = x_i \, \frac{x_i^2 + 3k}{3x_i^2 + k}
$$

This is a cubically convergent variant of Heron’s formula. Halley’s method requires fewer iterations to reach machine precision. Let's implement it using a simple stopping criterion based the distance between 2 consecutive machine numbers

In [1]:
from math import ulp  # Distance between 2 machine numbers
import numpy as np

There're 2 scenarios: either $x_{i + 1}$ can be exactly equal to $x_{i}$, or $x_{i + 1}$ oscillates between 2 machine numbers

In [2]:
def root_arr(k, n, x0, max_iter = 50): # Just for analysis

    x_old = x0
    x_array = np.zeros(max_iter + 1)
    x_array[0] = x0
    
    for j in range(1, max_iter + 1, 1):

        x_new = x_old * (x_old ** n * (n - 1.0) + k * (n + 1.0)) / (x_old ** n * (n + 1.0) + k * (n - 1.0)) # Basic step
        x_array[j] = x_new # Append result
        x_old = x_new # Update x_old

    return x_array # Returns the array

In [3]:
# Cubic root of 13
k = 13.0
n = 3.0
x0 = 1.0

x = root_arr(k, n, x0) # Convergence is fast
x

array([1.        , 1.8       , 2.32312682, 2.35133193, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469, 2.35133469, 2.35133469, 2.35133469, 2.35133469,
       2.35133469])

In [4]:
x[-1], x[-2], x[-3], x[-4], x[-5], x[-6] # Oscillations (last digit)

(np.float64(2.3513346877207573),
 np.float64(2.3513346877207577),
 np.float64(2.3513346877207573),
 np.float64(2.3513346877207577),
 np.float64(2.3513346877207573),
 np.float64(2.3513346877207577))

In [5]:
abs(x[-1] - x[-2]), ulp(x[-1]) # The difference is a ULP. It's not a general aspect though, it can be greater...see next example

(np.float64(4.440892098500626e-16), 4.440892098500626e-16)

In [6]:
# Cubic root of 188
k = 188.0
n = 3.0
x0 = 1.0

x = root_arr(k, n, x0)
x

array([1.        , 1.98421053, 3.74004887, 5.47419666, 5.72829667,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432, 5.72865432, 5.72865432, 5.72865432, 5.72865432,
       5.72865432])

In [7]:
x[-1], x[-2], x[-3], x[-4], x[-5], x[-6] # Oscillations (last digit)

(np.float64(5.728654315982438),
 np.float64(5.728654315982436),
 np.float64(5.728654315982438),
 np.float64(5.728654315982436),
 np.float64(5.728654315982438),
 np.float64(5.728654315982436))

In [8]:
abs(x[-1] - x[-2]), 2.0 * ulp(x[-1]) # The difference is twice ULP. There's a middle machine number we can compute!

(np.float64(1.7763568394002505e-15), 1.7763568394002505e-15)

In [9]:
m = (x[-1] + x[-2]) / 2.0 # Middle point
m - ulp(m), m, m + ulp(m) # The middle point is perfectly between them

(np.float64(5.728654315982436),
 np.float64(5.728654315982437),
 np.float64(5.728654315982438))

In [10]:
# Fifth root of 60
k = 60.0
n = 5.0
x0 = 1.0

x = root_arr(k, n, x0)
x

array([1.        , 1.4796748 , 2.0337917 , 2.26223095, 2.26793308,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316, 2.26793316, 2.26793316, 2.26793316, 2.26793316,
       2.26793316])

In [11]:
x[-1], x[-2], x[-3], x[-4], x[-5], x[-6] # Fixed value, no oscillatory behaviour

(np.float64(2.2679331552660544),
 np.float64(2.2679331552660544),
 np.float64(2.2679331552660544),
 np.float64(2.2679331552660544),
 np.float64(2.2679331552660544),
 np.float64(2.2679331552660544))

Let's handle these cases

In [12]:
def n_root(k, n, x0, max_iter = 50, verbose = True): # Implements Halley's method with estimated error

    step = lambda x: x * (x ** n * (n - 1.0) + k * (n + 1.0)) / (x ** n * (n + 1.0) + k * (n - 1.0)) # Basic step

    x_old = x0
    
    for j in range(1, max_iter + 1, 1):

        x_new = step(x_old) # One step
        diff = abs(x_new - x_old); error = ulp(x_new) # The error is 1 ULP

        if diff <= 2.0 * error: # Let's find a fixed value (if any)

            if diff == 0.0: # Fixed value suddenly reached
                if verbose: print("Fixed value detected, 1st shot")
                return (x_new, error, j)
            
            else: # Let's see forward, just give it a possibility
                x_new2 = step(x_new); x_new3 = step(x_new2) # 2 more steps
                diff = abs(x_new3 - x_new2); error = ulp(x_new3)

                if diff == 0.0: # Fixed value found
                    if verbose: print("Fixed value detected, 2nd shot")
                    return (x_new3, error, j + 2)
                else: # Oscillatory behaviour, no fixed value detected
                    if verbose: print("Oscillatory behaviour")
                    m = (x_new3 + x_new2) / 2.0 # Middle point
                    return (m, ulp(m), j + 2)

        x_old = x_new # Update x_old

    if verbose: print('Maximum number of iterations reached. The results are not reliable')
    return (x_new, error, j)

In [13]:
# Cubic root of 13
k = 13.0
n = 3.0
x0 = 1.0

n_root(k, n, x0), k ** (1 / n) # Oscillating

Oscillatory behaviour


((2.3513346877207573, 4.440892098500626e-16, 7), 2.3513346877207573)

In [14]:
# Cubic root of 188
k = 188.0
n = 3.0
x0 = 1.0

n_root(k, n, x0), k ** (1 / n) # Oscillating

Oscillatory behaviour


((5.728654315982437, 8.881784197001252e-16, 9), 5.728654315982437)

In [15]:
# Cubic root of 13
k = 60.0
n = 5.0
x0 = 1.0

n_root(k, n, x0), k ** (1 / n) # Fixed value

Fixed value detected, 2nd shot


((2.2679331552660544, 4.440892098500626e-16, 8), 2.2679331552660544)

Let's compute a table for $\sqrt[3]{k}$

In [16]:
for k in range(2, 216 + 1, 1): # Cubic root of all natural numbers between 2 and 215

    x0 = k / 20.0 # Initial value
    x, err, j = n_root(k, 3, x0, verbose = False)
    real = k ** (1 / 3)
    err_real = ulp(real) # Estimated roundoff error for k ** (1 / 3)

    print(f"\u221b{k} = {x:.16f} +- {err:.1g} ({j}) \t  {real:.16f} +- {err_real:.1g}")

∛2 = 1.2599210498948732 +- 2e-16 (8) 	  1.2599210498948732 +- 2e-16
∛3 = 1.4422495703074083 +- 2e-16 (7) 	  1.4422495703074083 +- 2e-16
∛4 = 1.5874010519681994 +- 2e-16 (9) 	  1.5874010519681994 +- 2e-16
∛5 = 1.7099759466766971 +- 2e-16 (9) 	  1.7099759466766968 +- 2e-16
∛6 = 1.8171205928321397 +- 2e-16 (9) 	  1.8171205928321397 +- 2e-16
∛7 = 1.9129311827723892 +- 2e-16 (7) 	  1.9129311827723889 +- 2e-16
∛8 = 2.0000000000000000 +- 4e-16 (8) 	  2.0000000000000000 +- 4e-16
∛9 = 2.0800838230519041 +- 4e-16 (6) 	  2.0800838230519041 +- 4e-16
∛10 = 2.1544346900318834 +- 4e-16 (8) 	  2.1544346900318838 +- 4e-16
∛11 = 2.2239800905693157 +- 4e-16 (6) 	  2.2239800905693152 +- 4e-16
∛12 = 2.2894284851066637 +- 4e-16 (6) 	  2.2894284851066637 +- 4e-16
∛13 = 2.3513346877207573 +- 4e-16 (8) 	  2.3513346877207573 +- 4e-16
∛14 = 2.4101422641752297 +- 4e-16 (8) 	  2.4101422641752297 +- 4e-16
∛15 = 2.4662120743304703 +- 4e-16 (8) 	  2.4662120743304699 +- 4e-16
∛16 = 2.5198420997897464 +- 4e-16 (6) 	  2

Let's compute a table for $\sqrt[4]{k}$

In [17]:
for k in range(2, 256 + 1, 1): # Fourth root of all natural numbers between 2 and 256

    x0 = k / 20.0 # Initial value
    x, err, j = n_root(k, 4, x0, verbose = False)
    real = k ** (1 / 4)
    err_real = ulp(real) # Estimated roundoff error for k ** (1 / 4)

    print(f"\u221c{k} = {x:.16f} +- {err:.1g} ({j}) \t  {real:.16f} +- {err_real:.1g}")

∜2 = 1.1892071150027212 +- 2e-16 (11) 	  1.1892071150027210 +- 2e-16
∜3 = 1.3160740129524924 +- 2e-16 (8) 	  1.3160740129524924 +- 2e-16
∜4 = 1.4142135623730949 +- 2e-16 (8) 	  1.4142135623730951 +- 2e-16
∜5 = 1.4953487812212205 +- 2e-16 (10) 	  1.4953487812212205 +- 2e-16
∜6 = 1.5650845800732871 +- 2e-16 (9) 	  1.5650845800732873 +- 2e-16
∜7 = 1.6265765616977856 +- 2e-16 (7) 	  1.6265765616977856 +- 2e-16
∜8 = 1.6817928305074290 +- 2e-16 (7) 	  1.6817928305074290 +- 2e-16
∜9 = 1.7320508075688772 +- 2e-16 (7) 	  1.7320508075688772 +- 2e-16
∜10 = 1.7782794100389230 +- 2e-16 (7) 	  1.7782794100389228 +- 2e-16
∜11 = 1.8211602868378720 +- 2e-16 (7) 	  1.8211602868378718 +- 2e-16
∜12 = 1.8612097182041991 +- 2e-16 (8) 	  1.8612097182041991 +- 2e-16
∜13 = 1.8988289221159418 +- 2e-16 (6) 	  1.8988289221159418 +- 2e-16
∜14 = 1.9343364202676692 +- 2e-16 (6) 	  1.9343364202676694 +- 2e-16
∜15 = 1.9679896712654306 +- 2e-16 (6) 	  1.9679896712654303 +- 2e-16
∜16 = 1.9999999999999998 +- 2e-16 (6) 	 

**Python can trick you sometimes...**

In [18]:
# Seventh root of -3111
k = -3111.0
n = 7.0
x0 = -1.0

x = root_arr(k, n, x0)
x

array([-1.        , -1.33308343, -1.77495902, -2.34255443, -2.92895549,
       -3.1498587 , -3.1549008 , -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086, -3.15490086, -3.15490086, -3.15490086, -3.15490086,
       -3.15490086])

In [19]:
x[-1], x[-2], x[-3], x[-4] # It suggests a fixed value for our algorithm

(np.float64(-3.1549008556582057),
 np.float64(-3.1549008556582057),
 np.float64(-3.1549008556582057),
 np.float64(-3.1549008556582057))

In [20]:
n_root(k, n, x0) # It works

Fixed value detected, 1st shot


(-3.1549008556582057, 4.440892098500626e-16, 8)

In [21]:
(- 3.1549008556582057) ** n # Test

-3110.999999999999

In [22]:
k ** (1 / n) # Python yields a complex number!

(2.8424674522667472+1.3688601797981659j)