### $e$ Taylor expansion error

Let $x$ be a positive number. Computing:

$$
    e^{x} \approx \sum_{k = 0}^{N} \, \frac{x^{k}}{k!}
$$

The total absolute upper bound error is:

$$
    E_{pos} \lesssim e^{x} \left[ \frac{x^{N + 1}}{\left( N + 1 \right)!} + u \left( 2 N + 1 + x \right) \right]
$$

Where $u$ is the machine precision.

Let $x$ be a negative number. Then we can compute:

$$
    e^{x} = \frac{1}{e^{|x|}} \approx \frac{1}{\sum_{k = 0}^{N} \, \frac{|x|^{k}}{k!}}
$$

And the error is:

$$
    E_{neg} = \frac{E_{pos}(|x|)}{ \left( \sum_{k = 0}^{N} \, \frac{|x|^{k}}{k!}  \right)^{2}} + \frac{u}{\sum_{k = 0}^{N} \, \frac{|x|^{k}}{k!}}
$$

In [1]:
import numpy as np
from scipy.special import factorial

In [2]:
eps = 2 ** (- 53) # Machine epsilon

def taylor(x, N): # It sums N terms to compute e^x

    global eps

    x_ = np.abs(x)
    k = np.arange(0, N + 1, 1)
    terms = x_ ** k / factorial(k)

    res = np.sum(terms)
    err = res * (x_ ** (N + 1) / factorial(N + 1) + eps * (x_ + 2.0 * N + 1.0)) # Error formula

    if x >= 0:
        return res, err
    else:
        return 1.0 / res, err / (res ** 2) + eps / res # Just applied the propagation error formula

In [3]:
x = - 1.0 # Compute 1 / e
res_array = np.array([taylor(x, N) for N in range(1, 100, 1)]) # Try different values of N
res_array

array([[5.00000000e-01, 2.50000000e-01],
       [4.00000000e-01, 6.66666667e-02],
       [3.75000000e-01, 1.56250000e-02],
       [3.69230769e-01, 3.07692308e-03],
       [3.68098160e-01, 5.11247444e-04],
       [3.67910066e-01, 7.29980291e-05],
       [3.67883212e-01, 9.12408759e-06],
       [3.67879855e-01, 1.01377826e-06],
       [3.67879482e-01, 1.01377724e-07],
       [3.67879445e-01, 9.21615666e-09],
       [3.67879441e-01, 7.68013991e-10],
       [3.67879441e-01, 5.90790235e-11],
       [3.67879441e-01, 4.22103592e-12],
       [3.67879441e-01, 2.82589560e-13],
       [3.67879441e-01, 1.89305276e-14],
       [3.67879441e-01, 2.46377611e-15],
       [3.67879441e-01, 1.56864429e-15],
       [3.67879441e-01, 1.59589428e-15],
       [3.67879441e-01, 1.67470694e-15],
       [3.67879441e-01, 1.75624857e-15],
       [3.67879441e-01, 1.83792734e-15],
       [3.67879441e-01, 1.91961268e-15],
       [3.67879441e-01, 2.00129831e-15],
       [3.67879441e-01, 2.08298395e-15],
       [3.678794

In [4]:
res = res_array[np.argmin(res_array[:,1])] # Minimum error
print(f"result = {res[0]:.15f} +- {res[1]:.15f}")
print(f"1 / e = {(1 / np.e):.15f}")
print(f"Best N: {np.argmin(res_array[:,1]) + 1}")

result = 0.367879441171442 +- 0.000000000000002
1 / e = 0.367879441171442
Best N: 17


In [5]:
x = 0.5 # Compute sqrt(e)
res_array = np.array([taylor(x, N) for N in range(1, 100, 1)]) # Different values of N
res_array

array([[1.50000000e+00, 1.87500000e-01],
       [1.62500000e+00, 3.38541667e-02],
       [1.64583333e+00, 4.28602431e-03],
       [1.64843750e+00, 4.29280599e-04],
       [1.64869792e+00, 3.57790347e-05],
       [1.64871962e+00, 2.55567897e-06],
       [1.64872117e+00, 1.59730089e-07],
       [1.64872127e+00, 8.87389739e-09],
       [1.64872127e+00, 4.43698280e-10],
       [1.64872127e+00, 2.01718769e-11],
       [1.64872127e+00, 8.44632445e-13],
       [1.64872127e+00, 3.69880621e-14],
       [1.64872127e+00, 6.18803354e-15],
       [1.64872127e+00, 5.43829922e-15],
       [1.64872127e+00, 5.76711459e-15],
       [1.64872127e+00, 6.13203722e-15],
       [1.64872127e+00, 6.49809250e-15],
       [1.64872127e+00, 6.86418121e-15],
       [1.64872127e+00, 7.23027085e-15],
       [1.64872127e+00, 7.59636051e-15],
       [1.64872127e+00, 7.96245017e-15],
       [1.64872127e+00, 8.32853984e-15],
       [1.64872127e+00, 8.69462950e-15],
       [1.64872127e+00, 9.06071916e-15],
       [1.648721

In [6]:
res = res_array[np.argmin(res_array[:,1])] # Minimum error
print(f"result = {res[0]:.15f} +- {res[1]:.15f}")
print(f"sqrt(e) = {(np.sqrt(np.e)):.15f}")
print(f"Best N: {np.argmin(res_array[:,1]) + 1}")

result = 1.648721270700128 +- 0.000000000000005
sqrt(e) = 1.648721270700128
Best N: 14


In [7]:
x = 3 # Compute e^3
res_array = np.array([taylor(x, N) for N in range(1, 100, 1)]) # Different values of N
res_array

array([[4.00000000e+00, 1.80000000e+01],
       [8.50000000e+00, 3.82500000e+01],
       [1.30000000e+01, 4.38750000e+01],
       [1.63750000e+01, 3.31593750e+01],
       [1.84000000e+01, 1.86300000e+01],
       [1.94125000e+01, 8.42363839e+00],
       [1.98464286e+01, 3.22947465e+00],
       [2.00091518e+01, 1.08531783e+00],
       [2.00633929e+01, 3.26477978e-01],
       [2.00796652e+01, 8.91116634e-02],
       [2.00841031e+01, 2.22828396e-02],
       [2.00852126e+01, 5.14247782e-03],
       [2.00854686e+01, 1.10197358e-03],
       [2.00855235e+01, 2.20395318e-04],
       [2.00855344e+01, 4.13241448e-05],
       [2.00855365e+01, 7.29249695e-06],
       [2.00855369e+01, 1.21541625e-06],
       [2.00855369e+01, 1.91907906e-07],
       [2.00855369e+01, 2.87862661e-08],
       [2.00855369e+01, 4.11240847e-09],
       [2.00855369e+01, 5.60872171e-10],
       [2.00855369e+01, 7.32508973e-11],
       [2.00855369e+01, 9.25447963e-12],
       [2.00855369e+01, 1.21311491e-12],
       [2.008553

In [8]:
res = res_array[np.argmin(res_array[:,1])] # Minimum error
print(f"result = {res[0]:.13f} +- {res[1]:.13f}")
print(f"e^3 = {(np.e ** 3):.13f}")
print(f"Best N: {np.argmin(res_array[:,1]) + 1}")

result = 20.0855369231877 +- 0.0000000000001
e^3 = 20.0855369231877
Best N: 27


In [9]:
x = - 30.0 # Compute e^(- 30)
res_array = np.array([taylor(x, N) for N in range(1, 200, 1)]) # Different values of N
res_array

array([[3.22580645e-02, 1.45161290e+01],
       [2.07900208e-03, 9.35550936e+00],
       [2.00762899e-04, 6.77574784e+00],
       [2.58191113e-05, 5.22837004e+00],
       [4.14540420e-06, 4.19722175e+00],
       [7.97619266e-07, 3.46109789e+00],
       [1.78794388e-07, 2.90939975e+00],
       [4.57344859e-08, 2.48068752e+00],
       [1.31394978e-08, 2.13810131e+00],
       [4.18708527e-09, 1.85818902e+00],
       [1.46494345e-09, 1.62532027e+00],
       [5.58005613e-10, 1.42867867e+00],
       [2.29756871e-10, 1.26054316e+00],
       [1.01637905e-10, 1.11525689e+00],
       [4.80499108e-11, 9.88582841e-01],
       [2.41628912e-11, 8.77287040e-01],
       [1.28711756e-11, 7.78860683e-01],
       [7.23562883e-12, 6.91330152e-01],
       [4.27807003e-12, 6.13124071e-01],
       [2.65204029e-12, 5.42978402e-01],
       [1.71877992e-12, 4.79867438e-01],
       [1.16144181e-12, 4.22952782e-01],
       [8.16219501e-13, 3.71544990e-01],
       [5.95109535e-13, 3.25074271e-01],
       [4.491140

In [10]:
res = res_array[np.argmin(res_array[:,1])] # Minimum error
print(f"result = {res[0]:.27f} +- {res[1]:.27f}")
print(f"e^(-30) = {(np.exp(- 30.0)):.27f}")
print(f"Best N: {np.argmin(res_array[:,1]) + 1}")

result = 0.000000000000093576229688402 +- 0.000000000000000000000000003
e^(-30) = 0.000000000000093576229688402
Best N: 109


In [11]:
def N_opt(x): # Computes the best values of N
    global eps

    best_N = 1
    while np.abs(x) ** (best_N + 1) / factorial(best_N + 1) > eps:
        best_N += 1

    return best_N

When $N$ is sufficient large, the error reaches a minimum. $N_{opt}$ can be computed roughly as:

$$
    \frac{|x| ^ {N_{opt} + 1}}{\left( N_{opt} + 1 \right)!} \approx u
$$

In [12]:
N_opt(- 1.0), N_opt(0.5), N_opt(3.0), N_opt(- 30.0) # Our best Ns estimations

(18, 14, 27, 110)