### Neumann Series

Given a real square matrix $T$, the Neumann series is an operator defined as:

$$
    N \triangleq \sum_{k = 0}^{\infty} \, T^k
$$

If the spectral radius of $T$ is less than 1, the Neumann series converges to:

$$
    N = \left( I - T \right)^{-1}
$$

Where $I$ is the identity matrix.

The spectral radius of $T$ is defined as the maximum of the absolute values of its eigenvalues:

$$
    \rho(T) \triangleq \text{max} \left\{ |\lambda_1|, |\lambda_2|, |\lambda_3|, \dots, |\lambda_n| \right\}
$$

$N$ is finite if:

$$
    \rho(T) < 1
$$

We can use this to solve linear systems. Consider:

$$
    A x = b
$$

Define:

$$
    H \triangleq I - A
$$

So, the solution can be computed as:

$$
    x = \left( I - H \right)^{-1} b
$$

If $\rho(H) < 1$, we can write:

$$
    \left( I - H \right)^{-1} = \sum_{k = 0}^{\infty} \, H^k
$$

And the solution is:

$$
    x = \sum_{k = 0}^{\infty} \, H^{k} b \qquad \rho(H) < 1
$$

In [1]:
import numpy as np

In [2]:
n = 100 # A has dimension 100 x 100

A = np.random.rand(n, n) / n # Random matrix
A = A @ (A.T) + np.eye(n)  # Symmetric positive definite
b = 2.0 * np.random.rand(n) # Random vector

A, b

(array([[1.00307925, 0.00203726, 0.0024773 , ..., 0.00212214, 0.00209398,
         0.0023179 ],
        [0.00203726, 1.00253728, 0.0022553 , ..., 0.00208126, 0.00188795,
         0.00203871],
        [0.0024773 , 0.0022553 , 1.00370886, ..., 0.00246851, 0.00241798,
         0.00268719],
        ...,
        [0.00212214, 0.00208126, 0.00246851, ..., 1.00307419, 0.00212929,
         0.00214677],
        [0.00209398, 0.00188795, 0.00241798, ..., 0.00212929, 1.00288243,
         0.00235072],
        [0.0023179 , 0.00203871, 0.00268719, ..., 0.00214677, 0.00235072,
         1.00312983]], shape=(100, 100)),
 array([0.36775992, 0.40074598, 1.93647226, 0.21550932, 1.77702249,
        1.2204272 , 1.30741753, 0.84761512, 1.06754597, 1.48188158,
        1.65354288, 1.22619085, 1.45894343, 1.62378527, 0.57365427,
        0.96782462, 1.55174993, 1.69181534, 0.84861035, 0.09815281,
        1.15355501, 1.6742165 , 0.64863627, 1.76152102, 0.39468326,
        1.9559538 , 0.21820562, 0.97068344, 0.13723

In [3]:
H = np.eye(n) - A # H = I - A
H

array([[-0.00307925, -0.00203726, -0.0024773 , ..., -0.00212214,
        -0.00209398, -0.0023179 ],
       [-0.00203726, -0.00253728, -0.0022553 , ..., -0.00208126,
        -0.00188795, -0.00203871],
       [-0.0024773 , -0.0022553 , -0.00370886, ..., -0.00246851,
        -0.00241798, -0.00268719],
       ...,
       [-0.00212214, -0.00208126, -0.00246851, ..., -0.00307419,
        -0.00212929, -0.00214677],
       [-0.00209398, -0.00188795, -0.00241798, ..., -0.00212929,
        -0.00288243, -0.00235072],
       [-0.0023179 , -0.00203871, -0.00268719, ..., -0.00214677,
        -0.00235072, -0.00312983]], shape=(100, 100))

In [4]:
def neumann_series(A, b, eps = 1e-09, max_iter = 100): # Solves Ax = b applying the Neumann series

    n = A.shape[0] # Dimension of A
    I = np.eye(n) # Identity matrix
    H = I - A # H Matrix

    # Check the spectral radius. It must be less than 1
    eigvals = np.linalg.eigvals(H)
    spectral_radius = np.max(np.abs(eigvals))
    if spectral_radius >= 1.0: raise ValueError(f"Neumann series does not converge: spectral radius = {spectral_radius} >= 1")

    x = np.zeros_like(b)
    term = b.copy()

    for j in range(max_iter): # Computing the Neumann series
        x += term
        
        residual = b - (A @ x) # Computing the residual b - A @ x
        residual_norm = np.linalg.norm(residual) # Computing the residual norm

        if residual_norm < eps: break # If the residual's norm is less than the tolerance threshold value, halt the loop

        term = H @ term # Update the next term

    else:
        print("Maximum number of iterations reached")

    info = { # General info
        "N iterations": j + 1,
        "Residual norm": residual_norm,
        "Spectral radius": spectral_radius,
        "Condition number of A": np.linalg.cond(A),
    }

    return x, info

In [5]:
neumann_sol, info = neumann_series(A, b) # Solution by Neumann series
neumann_sol, info

(array([ 0.18261173,  0.23110315,  1.72091194,  0.01978154,  1.57225747,
         1.01735261,  1.10737424,  0.65213492,  0.87594156,  1.27998826,
         1.475761  ,  1.0232243 ,  1.25465695,  1.42610175,  0.36489421,
         0.76144599,  1.33736473,  1.50224674,  0.65008917, -0.09761025,
         0.94464461,  1.46249712,  0.47131528,  1.55561373,  0.20088782,
         1.75398982,  0.03136406,  0.78582013, -0.03898019,  0.7459103 ,
        -0.00717283,  0.25084704,  1.63802193, -0.1817589 ,  1.73013517,
         0.96876432,  1.68034806,  0.23590244,  1.7793129 ,  1.09375056,
         0.05222976,  1.39171979,  1.56680232,  0.05448236,  0.23093318,
         0.98170715,  0.56595411,  0.82840905,  1.208333  ,  1.14747658,
         1.80841013,  1.24704097,  0.38991382,  1.73466049,  0.1190567 ,
         1.48655797,  1.55772814,  1.11892574,  0.08888566,  1.50868988,
         0.50683961,  0.17369153,  0.10635783,  0.52453076,  0.85207221,
         0.42325049, -0.16485992,  1.21246689,  1.6

In [6]:
numpy_sol = np.linalg.solve(A, b) # Solution by NumPy (direct solver)
numpy_sol

array([ 0.18261173,  0.23110315,  1.72091194,  0.01978154,  1.57225747,
        1.01735261,  1.10737424,  0.65213492,  0.87594156,  1.27998826,
        1.475761  ,  1.0232243 ,  1.25465695,  1.42610175,  0.36489421,
        0.76144599,  1.33736473,  1.50224674,  0.65008917, -0.09761025,
        0.94464461,  1.46249712,  0.47131528,  1.55561373,  0.20088782,
        1.75398982,  0.03136406,  0.78582013, -0.03898019,  0.7459103 ,
       -0.00717283,  0.25084704,  1.63802193, -0.1817589 ,  1.73013517,
        0.96876432,  1.68034806,  0.23590244,  1.7793129 ,  1.09375056,
        0.05222976,  1.39171979,  1.56680232,  0.05448236,  0.23093318,
        0.98170715,  0.56595411,  0.82840905,  1.208333  ,  1.14747658,
        1.80841013,  1.24704097,  0.38991382,  1.73466049,  0.1190567 ,
        1.48655797,  1.55772814,  1.11892574,  0.08888566,  1.50868988,
        0.50683961,  0.17369153,  0.10635783,  0.52453076,  0.85207221,
        0.42325049, -0.16485992,  1.21246689,  1.67666645,  1.10

In [7]:
np.max(np.abs(numpy_sol - neumann_sol)) # Maximum absolute error found

np.float64(5.63988855617481e-11)

To estimate a posteriori error vector $\varepsilon$ without knowing the true solution, we can solve:

$$
    A \varepsilon = b - A x^{*}
$$

Where $x^{*}$ is the approximated solution yield by our solver

In [8]:
residual = b - A @ neumann_sol # Computing the residual
abs_err = np.abs(neumann_series(A, residual, eps = 1e-13)[0]) # Absolute error vector
rel_err = abs_err / np.abs(neumann_sol) * 100.0 # Relative error vector
abs_err, rel_err

(array([4.80781867e-11, 4.38756127e-11, 5.53460770e-11, 5.08969413e-11,
        5.26304002e-11, 5.20749669e-11, 5.13214656e-11, 5.05187779e-11,
        4.94421980e-11, 5.18453296e-11, 4.57521424e-11, 5.24712530e-11,
        5.29032699e-11, 5.07160873e-11, 5.38053712e-11, 5.30435978e-11,
        5.52870069e-11, 4.87064620e-11, 5.15862653e-11, 5.08704417e-11,
        5.40304717e-11, 5.44020400e-11, 4.58609552e-11, 5.30647701e-11,
        5.01452291e-11, 5.18151997e-11, 4.82639429e-11, 4.77873141e-11,
        4.57263949e-11, 4.99359019e-11, 5.36564794e-11, 5.25341497e-11,
        4.78071560e-11, 5.59836765e-11, 5.63155174e-11, 4.76469967e-11,
        5.39147998e-11, 4.97034019e-11, 5.53959514e-11, 4.90209189e-11,
        4.73675525e-11, 5.29546026e-11, 5.34276334e-11, 5.00637326e-11,
        5.12580054e-11, 5.42611774e-11, 5.20310677e-11, 4.78984512e-11,
        5.30712700e-11, 5.41431844e-11, 4.78470209e-11, 5.10771863e-11,
        5.13872663e-11, 5.41671576e-11, 5.13302360e-11, 5.099815

Let's test slow convergence

In [9]:
A = np.array([[0.9, 0.4, 0.5],
              [0.3, 0.9, 0.6],
              [0.4, 0.5, 0.9]])
b = np.array([2.0, -1.0, 3.0])

neumann_series(A, b)

(array([ 1.4619883 , -5.38011696,  5.67251462]),
 {'N iterations': 97,
  'Residual norm': np.float64(9.441951265188194e-10),
  'Spectral radius': np.float64(0.8000000000000009),
  'Condition number of A': np.float64(5.400291037088579)})

In [10]:
# Error estimation
neumann_series(A, b - (A @ (neumann_series(A, b)[0])), eps = 1e-13)

(array([-3.02825921e-10, -3.02821947e-10, -3.02826914e-10]),
 {'N iterations': 42,
  'Residual norm': np.float64(8.032323709518985e-14),
  'Spectral radius': np.float64(0.8000000000000009),
  'Condition number of A': np.float64(5.400291037088579)})