Given a square linear system $A \, \vec{x} = \vec{b}$, the error $\vec{\varepsilon}$ of the solution $\vec{X}$, computed numerically, solves the linear system:

$$
    A \, \vec{\varepsilon} = \vec{r}
$$

Where $\vec{r} = \vec{b} - A \, \vec{X}$

In [1]:
import numpy as np

In [2]:
def gauss(A, b): # Gauss elimination algorithm from scratch

    # Convert to float and check dimensions
    A = np.asarray(A, dtype = float)
    b = np.asarray(b, dtype = float).flatten()

    n = A.shape[0] # Dimensions of A

    # Dimensions check
    if A.shape != (n, n) or len(b) != n:
        raise ValueError("A must be square and b must have length N.")
    if n == 0:
        return np.array([])

    U = np.column_stack((A, b)) # Build the augmented matrix A | b

    # Forward elimination with partial pivoting
    for i in range(n):
        pivot = np.argmax(np.abs(U[i:, i])) + i
        if np.abs(U[pivot, i]) < 1e-12: # Instability detected
            raise np.linalg.LinAlgError("Matrix is singular.")

        U[[i, pivot]] = U[[pivot, i]] # Swap pivot row (does nothing if pivot == i)

        # Vectorized elimination: update all rows below 'i' at once
        factors = U[i + 1:, i] / U[i, i]
        U[i + 1:, i:] -= factors[:, np.newaxis] * U[i, i:]

    # Back substitution
    X = np.zeros(n)
    for i in range(n - 1, - 1, - 1):
        X[i] = (U[i, - 1] - np.dot(U[i, i + 1: n], X[i + 1:])) / U[i, i]

    return X

### Testing a random linear system

In [3]:
N = 100 # A has dimension 100 x 100

A = np.random.rand(N, N) # Random matrix
A = A @ (A.T) + np.eye(N)  # Symmetric positive definite
b = np.random.rand(N) # Random vector

A, b

(array([[35.01961172, 28.36150563, 24.92458186, ..., 27.18287209,
         25.44920416, 26.43591234],
        [28.36150563, 37.90568653, 27.25072007, ..., 28.6281112 ,
         28.5473221 , 26.57163041],
        [24.92458186, 27.25072007, 32.75514784, ..., 26.18700727,
         25.75324124, 23.25213046],
        ...,
        [27.18287209, 28.6281112 , 26.18700727, ..., 34.28052194,
         26.31317554, 25.10518422],
        [25.44920416, 28.5473221 , 25.75324124, ..., 26.31317554,
         37.4811877 , 25.48102475],
        [26.43591234, 26.57163041, 23.25213046, ..., 25.10518422,
         25.48102475, 33.00498521]], shape=(100, 100)),
 array([0.6548368 , 0.17735818, 0.52089276, 0.51906928, 0.32999782,
        0.45843319, 0.44738253, 0.16191992, 0.9391822 , 0.53217402,
        0.06862156, 0.03632449, 0.80823239, 0.92742219, 0.12240306,
        0.83403776, 0.29054771, 0.2065359 , 0.35187747, 0.78592914,
        0.69019628, 0.19891415, 0.63591058, 0.55222875, 0.58654306,
        0.05032

In [4]:
X = gauss(A, b) # Solution
X

array([ 0.07577106, -0.09421251,  0.03041851, -0.00580222,  0.05376763,
       -0.07422996,  0.0692443 ,  0.03524834,  0.17259657, -0.09731404,
       -0.00273646, -0.14649463,  0.10420262,  0.01017899, -0.0133059 ,
        0.07946092, -0.16358606, -0.06279195, -0.0022291 ,  0.19147213,
        0.03834742, -0.03925424,  0.00194365, -0.02090658, -0.08485175,
       -0.19245859, -0.10893574,  0.04408728,  0.08049432, -0.02789367,
       -0.05283504, -0.2135438 ,  0.1430349 , -0.06683775, -0.09916924,
        0.04615508,  0.09287592,  0.01661579,  0.07034632,  0.11017998,
        0.08877378, -0.01319951, -0.08088717, -0.06341998,  0.24195161,
       -0.02530335,  0.03346473,  0.04585629,  0.10520836, -0.10039661,
       -0.01954854, -0.05836939,  0.17252776, -0.02738568,  0.00172873,
       -0.20781186, -0.03438496, -0.16781931, -0.18686097,  0.01364078,
        0.23864837, -0.0111204 ,  0.20354234,  0.0813202 , -0.07978171,
       -0.10757022,  0.00103801, -0.06365817,  0.07772798, -0.18

In [5]:
np.linalg.solve(A, b) # Solution X from NumPy perfectly matches our solution

array([ 0.07577106, -0.09421251,  0.03041851, -0.00580222,  0.05376763,
       -0.07422996,  0.0692443 ,  0.03524834,  0.17259657, -0.09731404,
       -0.00273646, -0.14649463,  0.10420262,  0.01017899, -0.0133059 ,
        0.07946092, -0.16358606, -0.06279195, -0.0022291 ,  0.19147213,
        0.03834742, -0.03925424,  0.00194365, -0.02090658, -0.08485175,
       -0.19245859, -0.10893574,  0.04408728,  0.08049432, -0.02789367,
       -0.05283504, -0.2135438 ,  0.1430349 , -0.06683775, -0.09916924,
        0.04615508,  0.09287592,  0.01661579,  0.07034632,  0.11017998,
        0.08877378, -0.01319951, -0.08088717, -0.06341998,  0.24195161,
       -0.02530335,  0.03346473,  0.04585629,  0.10520836, -0.10039661,
       -0.01954854, -0.05836939,  0.17252776, -0.02738568,  0.00172873,
       -0.20781186, -0.03438496, -0.16781931, -0.18686097,  0.01364078,
        0.23864837, -0.0111204 ,  0.20354234,  0.0813202 , -0.07978171,
       -0.10757022,  0.00103801, -0.06365817,  0.07772798, -0.18

In [6]:
res = b - A @ X # Residual vector
res

array([-6.66133815e-16, -9.32587341e-15,  4.21884749e-15, -1.23234756e-14,
       -9.32587341e-15, -9.54791801e-15, -1.13242749e-14,  2.22044605e-15,
        1.73194792e-14,  1.94289029e-14, -7.77156117e-16, -3.55271368e-15,
        1.25455202e-14,  5.21804822e-15, -5.88418203e-15, -4.66293670e-15,
        3.21964677e-15, -6.21724894e-15, -1.25455202e-14,  1.98729921e-14,
        4.10782519e-15, -7.54951657e-15, -1.50990331e-14,  1.21014310e-14,
       -1.39888101e-14, -1.36557432e-14,  1.99840144e-15, -5.55111512e-15,
        7.77156117e-16,  7.88258347e-15, -3.33066907e-15,  8.88178420e-16,
        6.88338275e-15,  2.44249065e-15, -1.02140518e-14,  2.10942375e-15,
       -4.10782519e-15, -1.33226763e-15,  2.10942375e-15, -2.22044605e-15,
        9.32587341e-15,  5.21804822e-15,  4.66293670e-15, -4.44089210e-16,
       -1.02140518e-14, -3.10862447e-15, -8.65973959e-15, -4.66293670e-15,
        9.65894031e-15, -1.39888101e-14, -5.99520433e-15,  1.58761893e-14,
        8.21565038e-15, -

In [7]:
errors = np.abs(gauss(A, res)) # Error estimation (taking absolute values)
errors

array([8.08481994e-16, 7.00451782e-15, 2.33717678e-15, 1.30414209e-15,
       2.27174830e-16, 7.35238666e-16, 2.09662267e-15, 7.26560846e-16,
       5.26600659e-15, 3.07043760e-16, 1.73540750e-16, 3.01952481e-15,
       5.33826083e-15, 2.84581837e-15, 1.76549986e-15, 3.52234923e-15,
       5.55002427e-15, 4.85060327e-16, 5.53582948e-15, 8.12172143e-15,
       6.54666792e-16, 2.70052212e-16, 3.81512032e-15, 5.03478173e-15,
       4.34752853e-15, 8.63257655e-16, 2.32731623e-15, 8.13503246e-17,
       9.03431997e-16, 5.68485737e-15, 4.35986834e-15, 2.06666846e-15,
       1.34709658e-15, 3.75698897e-15, 1.42506835e-15, 4.62663895e-16,
       8.84797796e-16, 2.83141608e-15, 1.79707243e-15, 2.08117785e-15,
       1.94827336e-15, 9.90067469e-16, 1.37952583e-15, 6.55219453e-16,
       4.98019760e-16, 2.93659872e-15, 3.10798586e-15, 1.27528824e-15,
       6.33950748e-15, 1.93252351e-15, 1.76074316e-15, 7.39497220e-15,
       3.94634386e-15, 3.88960565e-15, 1.66964736e-15, 5.50481839e-16,
      

In [8]:
np.min(errors), np.max(errors) # Minimum and maximum estimated absolute error

(np.float64(8.135032458501894e-17), np.float64(1.0053015427468948e-14))

In [9]:
relative_errors = errors / np.abs(X) * 1e02 # Estimated relative errors [%]
relative_errors

array([1.06700631e-12, 7.43480627e-12, 7.68340410e-12, 2.24765886e-11,
       4.22512288e-13, 9.90487693e-13, 3.02786340e-12, 2.06126254e-12,
       3.05104940e-12, 3.15518470e-13, 6.34180733e-12, 2.06118468e-12,
       5.12296218e-12, 2.79577694e-11, 1.32685490e-11, 4.43280673e-12,
       3.39272451e-12, 7.72488108e-13, 2.48344003e-10, 4.24172518e-12,
       1.70719901e-12, 6.87956852e-13, 1.96286881e-10, 2.40822799e-11,
       5.12367584e-12, 4.48542020e-13, 2.13641193e-12, 1.84521088e-13,
       1.12235497e-12, 2.03804551e-11, 8.25184976e-12, 9.67796046e-13,
       9.41795720e-13, 5.62105879e-12, 1.43700637e-12, 1.00241173e-12,
       9.52666545e-13, 1.70405191e-11, 2.55460749e-12, 1.88888927e-12,
       2.19464952e-12, 7.50078843e-12, 1.70549390e-12, 1.03314357e-12,
       2.05834449e-13, 1.16055724e-11, 9.28734811e-12, 2.78105391e-12,
       6.02566901e-12, 1.92488915e-12, 9.00703262e-12, 1.26692635e-11,
       2.28736744e-12, 1.42030643e-11, 9.65824662e-11, 2.64894335e-13,
      

In [10]:
np.min(relative_errors), np.max(relative_errors) # Minimum and maximum relative errors [%]

(np.float64(1.845210879799647e-13), np.float64(2.292517830816495e-09))

### Testing the inverse matrix

In [11]:
A = 2.0 * np.eye(3) + np.eye(3, k = 1) + np.eye(3, k = - 1) # Matrix target
A

array([[2., 1., 0.],
       [1., 2., 1.],
       [0., 1., 2.]])

In [12]:
# Known vectors
e1, e2, e3 = (np.array([1.,
                       0.,
                       0.]),
              np.array([0.,
                        1.,
                        0.]),
              np.array([0.,
                        0.,
                        1.]),)

e1, e2, e3

(array([1., 0., 0.]), array([0., 1., 0.]), array([0., 0., 1.]))

In [13]:
row1, row2, row3 = gauss(A, e1), gauss(A, e2), gauss(A, e3) # A^{-1}
row1, row2, row3

(array([ 0.75, -0.5 ,  0.25]),
 array([-0.5,  1. , -0.5]),
 array([ 0.25, -0.5 ,  0.75]))

In [14]:
np.linalg.inv(A) # Inverse of A using NumPy

array([[ 0.75, -0.5 ,  0.25],
       [-0.5 ,  1.  , -0.5 ],
       [ 0.25, -0.5 ,  0.75]])

In [15]:
# Computing absolute errors
res1, res2, res3 = e1 - A @ row1, e2 - A @ row2, e3 - A @ row3
err1, err2, err3 = np.abs(gauss(A, res1)), np.abs(gauss(A, res2)), np.abs(gauss(A, res3))

err1, err2, err3

(array([0.00000000e+00, 0.00000000e+00, 2.77555756e-17]),
 array([2.77555756e-17, 5.55111512e-17, 8.32667268e-17]),
 array([5.55111512e-17, 1.11022302e-16, 1.66533454e-16]))

In [16]:
err1 / np.abs(row1) * 1e02, err2 / np.abs(row2) * 1e02, err3 / np.abs(row3) * 1e02 # Relative errors [%]

(array([0.00000000e+00, 0.00000000e+00, 1.11022302e-14]),
 array([5.55111512e-15, 5.55111512e-15, 1.66533454e-14]),
 array([2.22044605e-14, 2.22044605e-14, 2.22044605e-14]))